import { Col, Row } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Menu from "../components/Menu/Menu";

import { MenuOutlined } from "@ant-design/icons";
import { useState } from "react";
const Home: NextPage = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const openMenu = (arg: boolean) => {
    setIsMenuOpen(arg);
  };
  return (
    <div>
      <Head>
        <title>Pâtisserie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container" style={{ paddingTop: "1rem" }}>
        <Row justify="center">
          <Col>
            <MenuOutlined
              style={{ fontSize: "1.5rem" }}
              onClick={() => openMenu(true)}
            ></MenuOutlined>
          </Col>
        </Row>
      </main>
      <Menu isMenuOpen={isMenuOpen} updateIsMenuOpen={openMenu}></Menu>
    </div>
  );
};

export default Home;
